# Generated by Django 5.2 on 2025-11-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('max_hp', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=10)),
                ('max_mp', models.IntegerField(default=0)),
                ('current_mp', models.IntegerField(default=0)),
                ('max_stamina', models.IntegerField(default=10)),
                ('current_stamina', models.IntegerField(default=10)),
                ('strength', models.IntegerField(default=10)),
                ('vitality', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('enemy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('max_hp', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=10)),
                ('max_mp', models.IntegerField(default=0)),
                ('current_mp', models.IntegerField(default=0)),
                ('role_class', models.CharField(max_length=10)),
                ('strength', models.IntegerField(default=10)),
                ('vitality', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('is_equippable', models.BooleanField(default=False)),
                ('is_consumable', models.BooleanField(default=False)),
                ('is_usable', models.BooleanField(default=False)),
                ('is_sellable', models.BooleanField(default=False)),
                ('is_buyable', models.BooleanField(default=False)),
                ('is_tradeable', models.BooleanField(default=False)),
                ('is_droppable', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('magic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('role_class', models.CharField(max_length=100)),
                ('mp_cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleClass',
            fields=[
                ('role_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_magical', models.BooleanField(default=False)),
                ('is_physical', models.BooleanField(default=False)),
                ('level_requirement', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaf_api.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaf_api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('enemies', models.ManyToManyField(to='jaf_api.enemy')),
                ('items', models.ManyToManyField(to='jaf_api.item')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='role_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaf_api.roleclass'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('items', models.ManyToManyField(to='jaf_api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cooldown', models.IntegerField(default=0)),
                ('stamina_cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaf_api.roleclass')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaf_api.user'),
        ),
    ]
