# Generated by Django 5.2 on 2025-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaf_api', '0002_rename_name_character_character_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
