# Generated by Django 5.2 on 2025-11-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaf_api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
